CREATE TABLE [dbo].[O_Org] (
	[ID] int NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED, 
	[OrgAgencyName] nvarchar(50) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[AgencyState] int NOT NULL DEFAULT ((0)), 
	[AgencyCounty] int NOT NULL DEFAULT ((0)), 
	[AgencyTown] int NOT NULL DEFAULT ((0)), 
	[AgencyVillage] int NOT NULL DEFAULT ((0)), 
	[AgencyAddress] nvarchar(30) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[AgencyPhoneNumber] nvarchar(15) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[BusinessState] int NOT NULL DEFAULT ((0)), 
	[AgencyCode] varchar(10) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[OrgID] int NOT NULL DEFAULT ((0)), 
	[DepartmentIDs] nvarchar(50) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT ((50)), 
	[OrgCateID] int NOT NULL DEFAULT ((0)), 
	[PID] int NOT NULL DEFAULT ((0)), 
	[OrgLevel] int NOT NULL DEFAULT ((0)), 
	[OrderNumber] int NOT NULL DEFAULT ((0)), 
	[DepartmentOther] nvarchar(10) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[ReportingType] int NOT NULL DEFAULT ((0)), 
	[IsSimpleFlu] bit NOT NULL DEFAULT ((0)), 
	[InoculationSchedule] nvarchar(50) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[OrgAgencyEnName] varchar(20) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[OrgAgencyShortName] nvarchar(10) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[PhoneAreaCode] varchar(5) COLLATE Chinese_Taiwan_Stroke_CI_AS NOT NULL DEFAULT (''), 
	[AgencyCate] int NOT NULL DEFAULT ((0)), 
	[LogicDel] bit NOT NULL DEFAULT ((0))
) ON [PRIMARY]
